# Shell variables
# Generated by 'wal'
wallpaper="/home/xrito/wallpapers/nord-background/ign_cityRain.png"

# Special
background='#1b1e25'
foreground='#c6c6c8'
cursor='#c6c6c8'

# Colors
color0='#1b1e25'
color1='#667475'
color2='#947D74'
color3='#74857A'
color4='#617686'
color5='#738B8B'
color6='#7697A5'
color7='#c6c6c8'
color8='#626878'
color9='#667475'
color10='#947D74'
color11='#74857A'
color12='#617686'
color13='#738B8B'
color14='#7697A5'
color15='#c6c6c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
