--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/xrito/wallpapers/nord-background/ign_cityRain.png"

-- Special
background="#1b1e25"
foreground="#c6c6c8"
cursor="#c6c6c8"

-- Colors
color0="#1b1e25"
color1="#667475"
color2="#947D74"
color3="#74857A"
color4="#617686"
color5="#738B8B"
color6="#7697A5"
color7="#c6c6c8"
color8="#626878"
color9="#667475"
color10="#947D74"
color11="#74857A"
color12="#617686"
color13="#738B8B"
color14="#7697A5"
color15="#c6c6c8"
